version: '3'

services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - '8008:8008'
    networks:
      - matrix-net

  nginx:
    image: nginx:latest
    container_name: nginx-matrix
    restart: unless-stopped
    volumes:
      - ./nginx/matrix.nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - '80:80'
      - '443:443'
      - '8448:8448'
    networks:
      - matrix-net

networks:
  matrix-net:
    driver: bridge
